Repository LCSB-BioCore/COBREXA.jl, pull requests merged in 2021-05, with the labels that each got.

#268 add support for travis CI
  .travis.yml
Labels: do not merge

#284 Clean up hit-and-run sampling
  Project.toml
  src/COBREXA.jl
  src/analysis/sampling/affine_hit_and_run.jl
  src/analysis/sampling/hit_and_run.jl
  src/analysis/sampling/warmup.jl
  src/analysis/sampling/warmup_variability.jl
  src/base/solver.jl
  test/analysis/sampling/affine_hit_and_run.jl
  test/analysis/sampling/hit_and_run.jl
  test/analysis/sampling/warmup.jl
  test/analysis/sampling/warmup_variability.jl
  test/runtests.jl
Labels: quality

#251 Fix hit and run sampler
  src/analysis/sampling/affine_hit_and_run.jl
  src/analysis/sampling/hit_and_run.jl
  src/analysis/sampling/warmup.jl
  src/analysis/sampling/warmup_variability.jl
  src/base/solver.jl
  src/base/utils/StandardModel.jl
  test/analysis/sampling/affine_hit_and_run.jl
  test/analysis/sampling/hit_and_run.jl
  test/analysis/sampling/warmup_variability.jl
Labels: draft, enhancement, performance
