Repository LCSB-BioCore/COBREXA.jl, pull requests merged in 2021-07, with the labels that each got.

#349 Fix small things
  docs/src/index.md.template
  docs/src/tutorials/4_modifying.md
  src/base/types/Reaction.jl
  src/base/utils/Reaction.jl
  src/io/show/FluxVariabilitySummary.jl
  src/reconstruction/Reaction.jl
  src/reconstruction/community.jl
Labels: quality

#346 Change `set_bound` to `change_bound` to fit in with `CoreModel` functions
  docs/src/advanced/1_variants.md
  docs/src/notebooks/6_screening.jl
  docs/src/tutorials/4_modifying.md
  src/COBREXA.jl
  src/base/macros/change_bounds.jl
  src/reconstruction/CoreModel.jl
  src/reconstruction/CoreModelCoupled.jl
  src/reconstruction/StandardModel.jl
  src/reconstruction/modifications/generic.jl
  test/reconstruction/CoreModel.jl
  test/reconstruction/CoreModelCoupled.jl
  test/reconstruction/StandardModel.jl
Labels: quality

#378 formatting report fix: break the line after code quote properly
  .gitlab-ci.yml
Labels: quality

#379 Fix argument error in community model notebook
  docs/src/notebooks/7_community_model.jl
Labels: bug

#383 final doc fixes for 1.0.3
  docs/src/advanced/2_custom_model.md
  docs/src/functions.md
  src/base/macros/change_bounds.jl
  src/base/types/Reaction.jl
Labels: documentation

#395 improve jsonmodel speed + some extra cleanup
  src/base/types/CoreModel.jl
  src/base/types/CoreModelCoupled.jl
  src/base/types/JSONModel.jl
  src/base/types/MATModel.jl
  src/base/types/SBMLModel.jl
  src/base/types/StandardModel.jl
  src/base/types/abstract/MetabolicModel.jl
  src/reconstruction/CoreModel.jl
  src/reconstruction/CoreModelCoupled.jl
Labels: performance, quality

#399 unsupport `name` field in models
  src/base/types/Gene.jl
  src/base/types/Metabolite.jl
  src/base/types/Reaction.jl
  src/base/types/StandardModel.jl
  src/base/utils/StandardModel.jl
  src/reconstruction/CoreModelCoupled.jl
  test/base/types/Gene.jl
  test/base/types/Metabolite.jl
  test/base/types/Reaction.jl
  test/base/types/StandardModel.jl
Labels: code axing, quality
