Repository LCSB-BioCore/COBREXA.jl, pull requests merged in 2021-11, with the labels that each got.

#482 reflect the workflow change in contrib guide
  .github/CONTRIBUTING.md
Labels: documentation

#487 Reorganize the API docs to nice sections
  docs/make.jl
  docs/src/functions.md
  docs/src/functions/analysis.md
  docs/src/functions/base.md
  docs/src/functions/io.md
  docs/src/functions/reconstruction.md
  docs/src/functions/types.md
  docs/src/functions/utils.md
  docs/src/tutorials/4_modifying.md
  src/base/macros/serialized.jl
  src/reconstruction/SerializedModel.jl
Labels: documentation

#486 Polish solution for all QP problems
  test/analysis/minimize_metabolic_adjustment.jl
  test/analysis/parsimonious_flux_balance_analysis.jl
  test/runtests.jl
Labels: bug

#489 fix gitlab docs (attempt 3)
  docs/make.jl
Labels: documentation

#437 Add loopless FBA
  Project.toml
  src/analysis/modifications/crowding.jl
  src/analysis/modifications/loopless.jl
  src/base/constants.jl
  src/base/utils/Reaction.jl
  src/base/utils/looks_like.jl
  test/analysis/fba_with_crowding.jl
  test/analysis/loopless.jl
  test/base/utils/looks_like.jl
  test/runtests.jl
Labels: feature

#493 Fix the documentation and some small issues
  docs/Project.toml
  docs/src/notebooks/2_finding_balance.jl
  docs/src/tutorials/4_modifying.md
  src/analysis/modifications/crowding.jl
  src/analysis/modifications/loopless.jl
  src/analysis/modifications/moment.jl
  test/analysis/fba_with_crowding.jl
  test/analysis/loopless.jl
Labels: documentation, minor

#494 Polish the notebook/example sections
  docs/src/notebooks/2_finding_balance.jl
Labels: documentation

#519 Extend max-min driving force analysis
  docs/src/notebooks/9_max_min_driving_force_analysis.jl
  src/analysis/max_min_driving_force.jl
  test/analysis/max_min_driving_force.jl
  test/data_static.jl
Labels: minor

#530 added `change_objective!` function and tests
  src/reconstruction/CoreModel.jl
  src/reconstruction/CoreModelCoupled.jl
  src/reconstruction/StandardModel.jl
  test/reconstruction/CoreModel.jl
  test/reconstruction/StandardModel.jl
Labels: minor

#517 Improve `remove_XXX` functions
  src/reconstruction/CoreModel.jl
  src/reconstruction/CoreModelCoupled.jl
  src/reconstruction/StandardModel.jl
Labels: minor
