Repository LCSB-BioCore/COBREXA.jl, pull requests merged in 2022-10, with the labels that each got.

#679 fix docbuild: JuMP `MIN_SENSE` and `MAX_SENSE` disappeared
  docs/src/examples/05b_fba_mods.jl
Labels: bug, documentation, minor

#686 Delete moment algorithm modification
  src/analysis/modifications/moment.jl
  test/analysis/moment.jl
Labels: code axing, :x: breaking :x:

#680 switch tests julia from 1.7 to 1.8
  .gitlab-ci.yml
Labels: quality, minor
