Repository LCSB-BioCore/COBREXA.jl, pull requests merged in 2022-02, with the labels that each got.

#566 Add `names` field to genes, metabolites and reaction types.
  src/base/types/Gene.jl
  src/base/types/JSONModel.jl
  src/base/types/Metabolite.jl
  src/base/types/Reaction.jl
  src/base/types/StandardModel.jl
  src/base/types/abstract/MetabolicModel.jl
Labels: minor

#579 Fix small error
  docs/src/notebooks/5_basic_stdmodel_construction.jl
  src/base/types/Reaction.jl
Labels: documentation, minor

#585 banner again!
  src/COBREXA.jl
  src/banner.jl
Labels: quality, minor
