Repository LCSB-BioCore/COBREXA.jl, pull requests merged in 2022-05, with the labels that each got.

#612 Update mods to handle gecko model
  src/base/types/MetabolicModel.jl
  src/base/types/wrappers/GeckoModel.jl
  src/base/utils/enzymes.jl
  test/analysis/gecko.jl
Labels: minor

#615 Check format using github actions, implement the `/format` command
  .github/workflows/pr-cmd-format.yml
  .github/workflows/pr-formatcheck.yml
  .gitlab-ci.yml
  src/analysis/gecko.jl
  src/base/types/wrappers/GeckoModel.jl
  src/base/utils/gecko.jl
  test/analysis/gecko.jl
Labels: quality

#617 Add a gap filling algorithm
  src/base/solver.jl
  src/reconstruction/gapfill_minimum_reactions.jl
  test/reconstruction/gapfill_minimum_reactions.jl
Labels: feature

#622 Fix small error with gapfill modifications
  src/reconstruction/gapfill_minimum_reactions.jl
Labels: bug
