Repository LCSB-BioCore/COBREXA.jl, pull requests merged in 2022-08, with the labels that each got.

#642 HDF5 model storage and fast memory mapping support
  .gitignore
  Project.toml
  src/COBREXA.jl
  src/base/types/HDF5Model.jl
  src/base/utils/HDF5Model.jl
  src/io/h5.jl
  src/io/io.jl
  test/io/h5.jl
Labels: performance, feature

#644 extend the autoformatting priveleges a bit
  .github/workflows/pr-format.yml
Labels: quality

#628 docs reorganization
  .gitignore
  README.md
  docs/Project.toml
  docs/make.jl
  docs/src/advanced.md
  docs/src/concepts.md
  docs/src/concepts/1_screen.md
  docs/src/concepts/2_modifications.md
  docs/src/concepts/3_custom_models.md
  docs/src/concepts/4_wrappers.md
  docs/src/distributed.md
  docs/src/distributed/1_functions.md
  docs/src/distributed/2_parallel.md
  docs/src/distributed/3_slurm.md
  docs/src/distributed/4_serialized.md
  docs/src/examples.md
  docs/src/examples/01_loading.jl
  docs/src/examples/02_convert_save.jl
  docs/src/examples/03_exploring.jl
  docs/src/examples/03b_accessors.jl
  docs/src/examples/04_core_model.jl
  docs/src/examples/04_standardmodel.jl
  docs/src/examples/04b_standardmodel_construction.jl
  docs/src/examples/05a_fba.jl
  docs/src/examples/05b_fba_mods.jl
  docs/src/examples/06_fva.jl
  docs/src/examples/07_gene_deletion.jl
  docs/src/examples/07_restricting_reactions.jl
  docs/src/examples/08_pfba.jl
  docs/src/examples/09_loopless.jl
  docs/src/examples/10_crowding.jl
  docs/src/examples/11_growth.jl
  docs/src/examples/12_mmdf.jl
  docs/src/examples/13_moma.jl
  docs/src/examples/14_smoment.jl
  docs/src/examples/15_gecko.jl
  docs/src/examples/16_hit_and_run.jl
  docs/src/examples/17_envelopes.jl
  docs/src/functions.md
  docs/src/index.md.template
  docs/src/notebooks.md
  docs/src/notebooks/1_loading_converting_saving.jl
  docs/src/notebooks/2_finding_balance.jl
  docs/src/notebooks/4_basic_core_coupled_usage.jl
  docs/src/notebooks/6_screening.jl
  docs/src/notebooks/7_community_model.jl
  docs/src/notebooks/8_custom_model.jl
  docs/src/notebooks/9_max_min_driving_force_analysis.jl
  docs/src/quickstart.md
  docs/src/quickstart.md.template
  docs/src/tutorials.md
  docs/src/tutorials/1_loading.md
  docs/src/tutorials/2_analysis.md
  docs/src/tutorials/3_hpc.md
  docs/src/tutorials/4_modifying.md
  src/analysis/envelopes.jl
  src/analysis/sampling/affine_hit_and_run.jl
  test/analysis/envelopes.jl
Labels: documentation

#656 hotfix: bump CompatHelper version to work with 1.8
  .github/workflows/CompatHelper.yml
Labels: quality

#658 Update compathelper CI script
  .github/workflows/CompatHelper.yml
Labels: quality

#659 Fix pFBA issue with return type nothing
  src/analysis/parsimonious_flux_balance_analysis.jl
Labels: bug

#654 Add some constructors
  src/base/types/Gene.jl
  src/base/types/Metabolite.jl
Labels: minor
