Repository LCSB-BioCore/COBREXA.jl, pull requests merged in 2022-09, with the labels that each got.

#662 add an explanation of what happens when you gapfill a feasible model
  src/reconstruction/gapfill_minimum_reactions.jl
Labels: documentation

#649 Remove the banner
  src/COBREXA.jl
  src/banner.jl
Labels: documentation, minor

#637 remove lots of lb/ub shortcuts from API
  src/analysis/flux_variability_analysis.jl
  src/analysis/minimize_metabolic_adjustment.jl
  src/analysis/modifications/generic.jl
  src/analysis/modifications/knockout.jl
  src/base/solver.jl
  src/base/types/Reaction.jl
  src/base/types/StandardModel.jl
  src/base/utils/StandardModel.jl
  src/io/show/Reaction.jl
  src/reconstruction/CoreModel.jl
  src/reconstruction/StandardModel.jl
  src/reconstruction/community.jl
  src/reconstruction/gapfill_minimum_reactions.jl
  test/analysis/fba_with_crowding.jl
  test/analysis/flux_balance_analysis.jl
  test/analysis/flux_variability_analysis.jl
  test/analysis/gecko.jl
  test/analysis/knockouts.jl
  test/analysis/moment.jl
  test/analysis/parsimonious_flux_balance_analysis.jl
  test/base/types/Reaction.jl
  test/base/types/StandardModel.jl
  test/base/utils/StandardModel.jl
  test/reconstruction/CoreModel.jl
  test/reconstruction/Reaction.jl
  test/reconstruction/StandardModel.jl
  test/reconstruction/add_reactions.jl
  test/reconstruction/community.jl
Labels: do not merge, quality, :x: breaking :x:

#676 Make the SBML annotations work just like with JSON models
  Project.toml
  src/base/types/SBMLModel.jl
Labels: quality
